version: "3"
services:
    node-app:
        build: .
        env_file:
            - ./.env
        depends_on:
            - mongo

    mongo:
        image: mongo
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
    
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes: 
    mongo-db: