version: "3"
services:
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_IP=mongo
            - MONGO_PORT=27017
            - MONGO_USER=mongousername
            - MONGO_PASSWORD=mongopassword
            - REDIS_SESSION_SECRET=secret
        command: npm run dev

    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mongousername
            - MONGO_INITDB_ROOT_PASSWORD=mongopassword

    nginx:
        ports:
            - "3000:80"